apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gke-vllm-serving
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/obaida7/gke-vllm-serving.git'
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kserve-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
