apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vllm-service-monitor
  namespace: kserve-test
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: qwen-vllm
  endpoints:
  - port: http
    interval: 10s
    path: /metrics
