apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: kserve-test
type: Opaque
stringData:
  POSTGRES_USER: litellm
  POSTGRES_PASSWORD: litellm-secure-password
  POSTGRES_DB: litellm
